### ISSUE TITLE
Crashes when trying to show help options.

### ISSUE THREAD

**Issue by KordianD** [ugursogukpinar/csv2arff#7]
Maybe I am doing something wrong but when I want to show help options.
**csv2arff -h**

Traceback (most recent call last):
  File "/home/user2/anaconda3/bin/csv2arff", line 11, in <module>
    sys.exit(main())
  File "/home/user2/anaconda3/lib/python3.6/site-packages/csv2arff/csv2arff.py", line 109, in main
    Csv2Arff(sys.argv[1], sys.argv[2])
IndexError: list index out of range

**Comment by ugursogukpinar** [comment]
It seems latest version of package was not uploaded. Can you please try it again? 

PS: You can upgrade it by: `pip install --upgrade csv2arff`

**Comment by KordianD** [comment]
Right now it is working.
